export const AIRLINES: Record<string, string> = {
  VN: "Vietnam Airlines",
  VJ: "VietJet Air",
  QH: "Bamboo Airways",
  BL: "Pacific Airlines",
  VU: "Vietravel Airlines",
  "0V": "VASCO",
  "9G": "Sun Phu Quoc Airways",
  AK: "AirAsia",
  FD: "Thai AirAsia",
  QZ: "Indonesia AirAsia",
  Z2: "Philippines AirAsia",
  KE: "Korean Air",
  OZ: "Asiana Airlines",
  "7C": "Jeju Air",
  TW: "T'way Air",
  LJ: "Jin Air",
  BX: "Air Busan",
  RS: "Air Seoul",
  BR: "EVA Air",
  CI: "China Airlines",
  JX: "STARLUX Airlines",
  CX: "Cathay Pacific",
  UO: "HK Express",
  MH: "Malaysia Airlines",
  OD: "Batik Air Malaysia",
  TR: "Scoot",
  SQ: "Singapore Airlines",
  PR: "Philippine Airlines",
  "5J": "Cebu Pacific",
  TG: "Thai Airways",
  VZ: "Thai Vietjet Air",
  PG: "Bangkok Airways",
  QV: "Lao Airlines",
  K6: "Cambodia Angkor Air",
  KR: "Cambodia Airways",
  ZA: "Sky Angkor Airlines",
  CZ: "China Southern Airlines",
  MU: "China Eastern Airlines",
  CA: "Air China",
  MF: "XiamenAir",
  ZH: "Shenzhen Airlines",
  HU: "Hainan Airlines",
  IT: "Tigerair Taiwan",
  NX: "Air Macau",
  JL: "Japan Airlines",
  NH: "All Nippon Airways",
  HB: "Greater Bay Airlines",
  "3K": "Jetstar Asia",
  JQ: "Jetstar Airways",
  EK: "Emirates",
  QR: "Qatar Airways",
  TK: "Turkish Airlines",
  // Thêm các hãng 3 ký tự (ICAO) phòng trường hợp data dùng ICAO
  HVN: "Vietnam Airlines",
  VJC: "VietJet Air",
  BAV: "Bamboo Airways",
  PIC: "Pacific Airlines",
  VAG: "Vietravel Airlines",
  VFC: "VASCO",
};

export function getAirlineName(code: string): string {
  const normalized = code.trim().toUpperCase();
  return AIRLINES[normalized] || normalized;
}
