import type { AirportInfo } from "./types";

const AIRPORTS: Record<string, AirportInfo> = {
  ALA: { code: "ALA", name: "Almaty International Airport", city: "Almaty", province: "Almaty", country: "Kazakhstan" },
  AMD: { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad", province: "Gujarat", country: "India" },
  BAX: { code: "BAX", name: "Barnaul Airport", city: "Barnaul", province: "Altai Krai", country: "Russia" },
  BKK: { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", province: "Bangkok", country: "Thailand" },
  BKI: { code: "BKI", name: "Kota Kinabalu International Airport", city: "Kota Kinabalu", province: "Sabah", country: "Malaysia" },
  BLR: { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", province: "Karnataka", country: "India" },
  BMV: { code: "BMV", name: "Buon Ma Thuot Airport", city: "Buon Ma Thuot", province: "Dak Lak", country: "Vietnam" },
  BOM: { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", province: "Maharashtra", country: "India" },
  CAH: { code: "CAH", name: "Ca Mau Airport", city: "Ca Mau", province: "Ca Mau", country: "Vietnam" },
  CAN: { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", province: "Guangdong", country: "China" },
  CCU: { code: "CCU", name: "Netaji Subhash Chandra Bose International Airport", city: "Kolkata", province: "West Bengal", country: "India" },
  CGK: { code: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", province: "Banten", country: "Indonesia" },
  CJJ: { code: "CJJ", name: "Cheongju International Airport", city: "Cheongju", province: "North Chungcheong", country: "South Korea" },
  CJU: { code: "CJU", name: "Jeju International Airport", city: "Jeju City", province: "Jeju", country: "South Korea" },
  CKG: { code: "CKG", name: "Chongqing Jiangbei International Airport", city: "Chongqing", province: "Chongqing", country: "China" },
  CNX: { code: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai", province: "Chiang Mai", country: "Thailand" },
  COK: { code: "COK", name: "Cochin International Airport", city: "Kochi", province: "Kerala", country: "India" },
  CTS: { code: "CTS", name: "New Chitose Airport", city: "Sapporo", province: "Hokkaido", country: "Japan" },
  CTU: { code: "CTU", name: "Chengdu Tianfu International Airport", city: "Chengdu", province: "Sichuan", country: "China" },
  CXR: { code: "CXR", name: "Cam Ranh International Airport", city: "Cam Ranh", province: "Khanh Hoa", country: "Vietnam" },
  DAD: { code: "DAD", name: "Da Nang International Airport", city: "Da Nang", province: "Da Nang", country: "Vietnam" },
  DEL: { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", province: "Delhi", country: "India" },
  DIN: { code: "DIN", name: "Dien Bien Airport", city: "Dien Bien Phu", province: "Dien Bien", country: "Vietnam" },
  DLI: { code: "DLI", name: "Lien Khuong Airport", city: "Da Lat", province: "Lam Dong", country: "Vietnam" },
  DMK: { code: "DMK", name: "Don Mueang International Airport", city: "Bangkok", province: "Bangkok", country: "Thailand" },
  DPS: { code: "DPS", name: "Ngurah Rai International Airport", city: "Bali", province: "Bali", country: "Indonesia" },
  FUK: { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", province: "Fukuoka", country: "Japan" },
  HAN: { code: "HAN", name: "Noi Bai International Airport", city: "Ha Noi", province: "Ha Noi", country: "Vietnam" },
  HGH: { code: "HGH", name: "Hangzhou Xiaoshan International Airport", city: "Hangzhou", province: "Zhejiang", country: "China" },
  HKG: { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", province: "Hong Kong", country: "Hong Kong" },
  HKT: { code: "HKT", name: "Phuket International Airport", city: "Phuket", province: "Phuket", country: "Thailand" },
  HND: { code: "HND", name: "Haneda Airport", city: "Tokyo", province: "Tokyo", country: "Japan" },
  HPH: { code: "HPH", name: "Cat Bi International Airport", city: "Hai Phong", province: "Hai Phong", country: "Vietnam" },
  HUI: { code: "HUI", name: "Phu Bai International Airport", city: "Hue", province: "Thua Thien Hue", country: "Vietnam" },
  HYD: { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", province: "Telangana", country: "India" },
  ICN: { code: "ICN", name: "Incheon International Airport", city: "Seoul", province: "Incheon", country: "South Korea" },
  KHH: { code: "KHH", name: "Kaohsiung International Airport", city: "Kaohsiung", province: "Kaohsiung", country: "Taiwan" },
  KHV: { code: "KHV", name: "Khabarovsk Novy Airport", city: "Khabarovsk", province: "Khabarovsk Krai", country: "Russia" },
  KIX: { code: "KIX", name: "Kansai International Airport", city: "Osaka", province: "Osaka", country: "Japan" },
  KJA: { code: "KJA", name: "Krasnoyarsk International Airport", city: "Krasnoyarsk", province: "Krasnoyarsk Krai", country: "Russia" },
  KMG: { code: "KMG", name: "Kunming Changshui International Airport", city: "Kunming", province: "Yunnan", country: "China" },
  KOS: { code: "KOS", name: "Sihanoukville International Airport", city: "Sihanoukville", province: "Preah Sihanouk", country: "Cambodia" },
  KTI: { code: "KTI", name: "Techo International Airport", city: "Phnom Penh", province: "Kandal", country: "Cambodia" },
  KUL: { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", province: "Selangor", country: "Malaysia" },
  KZN: { code: "KZN", name: "Kazan International Airport", city: "Kazan", province: "Tatarstan", country: "Russia" },
  LPQ: { code: "LPQ", name: "Luang Prabang International Airport", city: "Luang Prabang", province: "Luang Prabang", country: "Laos" },
  MFM: { code: "MFM", name: "Macau International Airport", city: "Macau", province: "Macau", country: "Macau" },
  MNL: { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", province: "Metro Manila", country: "Philippines" },
  NGO: { code: "NGO", name: "Chubu Centrair International Airport", city: "Nagoya", province: "Aichi", country: "Japan" },
  NKG: { code: "NKG", name: "Nanjing Lukou International Airport", city: "Nanjing", province: "Jiangsu", country: "China" },
  NNG: { code: "NNG", name: "Nanning Wuxu International Airport", city: "Nanning", province: "Guangxi", country: "China" },
  NOZ: { code: "NOZ", name: "Spichenkovo Airport", city: "Novokuznetsk", province: "Kemerovo Oblast", country: "Russia" },
  NQZ: { code: "NQZ", name: "Nursultan Nazarbayev International Airport", city: "Astana", province: "Astana", country: "Kazakhstan" },
  NRT: { code: "NRT", name: "Narita International Airport", city: "Tokyo", province: "Chiba", country: "Japan" },
  PEK: { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", province: "Beijing", country: "China" },
  PEN: { code: "PEN", name: "Penang International Airport", city: "George Town", province: "Penang", country: "Malaysia" },
  PKX: { code: "PKX", name: "Beijing Daxing International Airport", city: "Beijing", province: "Beijing", country: "China" },
  PNH: { code: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", province: "Phnom Penh", country: "Cambodia" },
  PQC: { code: "PQC", name: "Phu Quoc International Airport", city: "Phu Quoc", province: "Kien Giang", country: "Vietnam" },
  PUS: { code: "PUS", name: "Gimhae International Airport", city: "Busan", province: "Busan", country: "South Korea" },
  PVG: { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", province: "Shanghai", country: "China" },
  PXU: { code: "PXU", name: "Pleiku Airport", city: "Pleiku", province: "Gia Lai", country: "Vietnam" },
  RGN: { code: "RGN", name: "Yangon International Airport", city: "Yangon", province: "Yangon", country: "Myanmar" },
  RMQ: { code: "RMQ", name: "Taichung International Airport", city: "Taichung", province: "Taichung", country: "Taiwan" },
  SAI: { code: "SAI", name: "Siem Reap Angkor International Airport", city: "Siem Reap", province: "Siem Reap", country: "Cambodia" },
  SGN: { code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", province: "Ho Chi Minh City", country: "Vietnam" },
  SIN: { code: "SIN", name: "Changi Airport", city: "Singapore", province: "Singapore", country: "Singapore" },
  SVO: { code: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", province: "Moscow", country: "Russia" },
  TAE: { code: "TAE", name: "Daegu International Airport", city: "Daegu", province: "Daegu", country: "South Korea" },
  TAS: { code: "TAS", name: "Tashkent International Airport", city: "Tashkent", province: "Tashkent", country: "Uzbekistan" },
  TBB: { code: "TBB", name: "Tuy Hoa Airport", city: "Tuy Hòa", province: "Phú Yên", country: "Vietnam" },
  THD: { code: "THD", name: "Tho Xuan Airport", city: "Thanh Hóa", province: "Thanh Hóa", country: "Vietnam" },
  TNN: { code: "TNN", name: "Tainan Airport", city: "Tainan", province: "Tainan", country: "Taiwan" },
  TPE: { code: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", province: "Taoyuan", country: "Taiwan" },
  TSA: { code: "TSA", name: "Taipei Songshan Airport", city: "Taipei", province: "Taipei", country: "Taiwan" },
  UIH: { code: "UIH", name: "Phu Cat Airport", city: "Quy Nhơn", province: "Bình Định", country: "Vietnam" },
  VCA: { code: "VCA", name: "Can Tho International Airport", city: "Cần Thơ", province: "Cần Thơ", country: "Vietnam" },
  VCL: { code: "VCL", name: "Chu Lai Airport", city: "Chu Lai", province: "Quảng Nam", country: "Vietnam" },
  VCS: { code: "VCS", name: "Con Dao Airport", city: "Côn Đảo", province: "Bà Rịa - Vùng Tàu", country: "Vietnam" },
  VDH: { code: "VDH", name: "Dong Hoi Airport", city: "Đồng Hới", province: "Quảng Bình", country: "Vietnam" },
  VDO: { code: "VDO", name: "Van Don International Airport", city: "Vân Đồn", province: "Quảng Ninh", country: "Vietnam" },
  VII: { code: "VII", name: "Vinh Airport", city: "Vinh", province: "Nghệ An", country: "Vietnam" },
  VKG: { code: "VKG", name: "Rach Gia Airport", city: "Rạch Giá", province: "Kiên Giang", country: "Vietnam" },
  VTE: { code: "VTE", name: "Wattay International Airport", city: "Vientiane", province: "Vientiane", country: "Laos" },
  WUH: { code: "WUH", name: "Wuhan Tianhe International Airport", city: "Wuhan", province: "Hubei", country: "China" },
  XIY: { code: "XIY", name: "Xi'an Xianyang International Airport", city: "Xi'an", province: "Shaanxi", country: "China" },
  XSP: { code: "XSP", name: "Seletar Airport", city: "Singapore", province: "Singapore", country: "Singapore" },
  ZNZ: { code: "ZNZ", name: "Abeid Amani Karume International Airport", city: "Zanzibar", province: "Zanzibar", country: "Tanzania" },
};

export function getAirportInfo(code: string): AirportInfo {
  const normalized = code.trim().toUpperCase();
  return (
    AIRPORTS[normalized] ?? {
      code: normalized,
      name: normalized,
      city: "Chua xac dinh",
      province: "Chua xac dinh",
      country: "Chua xac dinh",
    }
  );
}

export function formatAirport(code: string): string {
  const airport = getAirportInfo(code);
  return `${airport.code} - ${airport.city}`;
}
